version: "3.4"

services:
  ui:
    build: ui
    image: ui
    restart: "no"
    volumes:
      - ./ui/src:/usr/app/src
      - ./ui/public:/usr/app/public
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - rabbitmq_nodejs

  api:
    build: api
    image: api
    restart: "on-failure"
    volumes:
      - ./api:/usr/app
    ports:
      - 4000:4000
    depends_on:
      - database
      - flyway
      - rabbitmq
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs

  database:
    container_name: dab-p2-database
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs


networks:
  rabbitmq_nodejs:
    driver: bridge
