version: "3.4"

services:
  ui:
    build: ui
    image: ui
    restart: "no"
    volumes:
      - ./ui/src:/usr/app/src
      - ./ui/public:/usr/app/public
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - rabbitmq_nodejs

  api:
    build: api
    image: api
    restart: "on-failure"
    volumes:
      - ./api:/usr/app
    ports:
      - 4000:4000
    depends_on:
      - database
      - flyway
      - rabbitmq
      - grader
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs

  grader:
    build: grader
    image: grader
    restart: "on-failure"
    volumes:
      - ./grader:/usr/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database
      - flyway
      - rabbitmq
      - redis
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs

  database:
    container_name: dab-p2-database
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    networks:
      - rabbitmq_nodejs
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs

  redis:
    image: redis:latest
    container_name: 'redis'
    restart: always
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf --bind redis --port 6379
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - cache:/data
    networks:
      - rabbitmq_nodejs

volumes:
  cache:
    driver: local


networks:
  rabbitmq_nodejs:
    driver: bridge
